before_script:
- apt update
- apt install -y git unzip
- curl https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar --output /usr/local/bin/phpcs
- curl https://getcomposer.org/composer.phar --output /usr/local/bin/composer
- curl https://phar.phpunit.de/phpunit-8.4.3.phar --output /usr/local/bin/phpunit
- chmod +x /usr/local/bin/phpcs /usr/local/bin/composer /usr/local/bin/phpunit

build:7.2:
  image: php:7.2
  script: ./build.sh

build:7.3:
  image: php:7.3
  script: ./build.sh
  artifacts:
    paths:
      - build/
    expire_in: 1 week

build:7.4:
  image: php:7.4
  script: ./build.sh
