image: php:7.2

before_script:
- curl https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar --output phpcs.phar

check:psr2:
  script:
  - php phpcs.phar --standard=PSR2 --extensions=php --warning-severity=0 .
