image: php:7.2

before_script:
- apt update
- apt install -y git unzip
- curl https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar --output /usr/local/bin/phpcs
- curl https://getcomposer.org/composer.phar --output /usr/local/bin/composer
- curl https://phar.phpunit.de/phpunit-8.4.3.phar --output /usr/local/bin/phpunit
- chmod +x /usr/local/bin/phpcs /usr/local/bin/composer /usr/local/bin/phpunit

check:psr2:
  script:
  - phpcs --standard=PSR2 --extensions=php --warning-severity=0 .

build:zip:
  script:
    - rm .gitignore
    - composer install --no-dev --no-interaction --no-suggest --ignore-platform-reqs
    - phpunit --testdox
    - composer archive --dir build/ --format=zip
  artifacts:
    paths:
        - build/
    expire_in: 1 week
